2020-04-10 11:57:05,051 - INFO - Номенклатура загрузилась
2020-04-10 11:57:05,183 - INFO - Остатки центрального склада загрузились
2020-04-10 11:57:05,212 - INFO - Остатки склада ТН загрузились
2020-04-10 11:57:05,239 - INFO - Поступления загрузились
2020-04-10 11:57:08,778 - INFO - Заказы ТН загрузилась
2020-04-10 11:57:08,822 - INFO - Потребность загрузилась
2020-04-10 11:58:54,298 - INFO - Таблицы подготовились: True
2020-04-10 11:58:54,301 - INFO - Отклонение аска: 112114.81764216999; Отклонение остатков: 112114.81764217002
2020-04-10 11:58:54,305 - INFO - Потребность / 207045 / 94930
2020-04-10 11:59:19,141 - INFO - Traceback (most recent call last):
  File "W:/Analytics/Илья/!repositories/calculation_metiz/daily_report.py", line 87, in <module>
    main()
  File "W:/Analytics/Илья/!repositories/calculation_metiz/daily_report.py", line 74, in main
    daily_tables()
  File "W:\Analytics\Илья\!repositories\calculation_metiz\reports\daily.py", line 27, in daily_tables
    deficit(output_req)
  File "W:\Analytics\Илья\!repositories\calculation_metiz\reports\daily.py", line 46, in deficit
    first_table = main_deficit_table(table)
  File "W:\Analytics\Илья\!repositories\calculation_metiz\reports\daily.py", line 81, in main_deficit_table
    problems = compare_with_prev_ask(table)  # готовая таблица с индикатором проблем (переносы, отклонение потреб)
  File "W:\Analytics\Илья\!repositories\calculation_metiz\reports\daily.py", line 148, in compare_with_prev_ask
    name_prev_file = [i for i in walk(path)][0][2][-1]
IndexError: list index out of range

